### ISSUE TITLE
Aiming at mouse + Trigger Collider issue

### ISSUE THREAD

**Issue by MattW92** [clumsyknightgames/cyberpunkshooter#1]
When aiming at a trigger collider the aim will shoot up into the sky due to it counting the trigger as a hit.

**Comment by MaeBee** [comment]
Fixed in be3bbdfff9d12bb4b729a649a1fa3b84dbfcadf9
Moved SphereCollider into a child GameObject and set that to layer 2 to ignore raycasts.
